### ISSUE TITLE
Suggestion: Run task when Yez! starts option

### ISSUE THREAD

**Issue by rafaelcastrocouto** [krasimir/yez#11]
Is it possible to make an option to run a task as soon as Yez! starts?

**Comment by krasimir** [comment]
At the moment there is no such feature. I'll leave this issue open and will tag it as `enhancement`.

**Comment by rafaelcastrocouto** [comment]
I've just implemented this as well ... :smile:

**Comment by krasimir** [comment]
@rafaelcastrocouto can we close this one?

**Comment by rafaelcastrocouto** [comment]
sure!
