### ISSUE TITLE
yez install hangs in my Windows 7 environment

### ISSUE THREAD

**Issue by sanori** [krasimir/yez#8]
```npm -g install yez``` hangs.
```npm install -g https://registry.npmjs.org/yez/-/yez-2.0.1.tgz``` and ```npm install yez``` (without -g) also hangs.

The messages during install is as follows:
```
C:\Users\user>npm install -g https://registry.npmjs.org/yez/-/yez-2.0.1.tgz
|


> ws@0.4.32 install C:\Users\user\AppData\Roaming\npm\node_modules\yez\node_mo
dules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\user\AppData\Roaming\npm\node_modules\yez\node_modules\socket.io\node
_modules\socket.io-client\node_modules\ws>node "C:\Program Files\nodejs\node_mod
ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

\  <- (windmill stopped)
```
What would be the problem?

**Comment by krasimir** [comment]
Hello @sanori what your Node.js version?

**Comment by sanori** [comment]
I just have found my problem!
It seems that node-gyp requires Microsoft Visual Studio (Express) 2012 or 2013 in Windows 7.

I have installed Visual Studio Express for Windows Desktop 2013 and the problem has solved.
npm install tries to compile bufferutil.cc and validation.cc.
It makes the install process hanging, I guess.

For your information, my node.js version is v0.10.36 (latest in 0.10.x).

Thank you for your fast response.

**Comment by krasimir** [comment]
No problem. Is everything ok now?

**Comment by sanori** [comment]
yez process and chome extension works well. (I tested Windows cmd and git BASH)
It seems that everything is OK.

Thanks.
